source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "robertmeta/plug.kak" noload

plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"
    hook global WinSetOption filetype=(c|cpp|rust|sh) %{
        map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
        lsp-enable-window
        lsp-auto-hover-disable
        lsp-auto-hover-insert-mode-disable
        lsp-auto-signature-help-enable
        set-option window lsp_hover_anchor false
    }
}

map global normal <c-e> ': lsp-definition<ret>' -docstring "jump to definition (LSP)"

hook global WinSetOption filetype=rust %{
    set buffer formatcmd "rustfmt --edition=2018"
}

map global normal '<c-f>' ': fzf-mode<ret>' -docstring 'fzf mode'
plug "andreyorst/fzf.kak" defer fzf %{
    set-option global fzf_preview_width '65%'
    set-option global fzf_file_command "fd --hidden --exclude '/.git/' --type f --follow"
    set-option global fzf_highlight_command "bat"
    set-option global fzf_grep_command "rg --hidden --glob '!/.git/' --line-number --no-column --no-heading --color=never ''"
    set-option global fzf_window_map "ctrl-t"
    set-option global fzf_use_main_selection false
}

add-highlighter global/ number-lines

declare-user-mode git
map global user v ': enter-user-mode git<ret>' -docstring 'git mode'

map global git s  ': git status<ret>'          -docstring 'status'
map global git d  ': git diff<ret>'            -docstring 'diff'
map global git l  ': git log<ret>'             -docstring 'log'

